
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lecox
 */
public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
         this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextCadastro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonCadastro = new javax.swing.JButton();
        ButtonMenu = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboqtd = new javax.swing.JComboBox<>();
        TextPreco = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(TextCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 60, 338, -1));

        jLabel1.setText("Produto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 40, 338, -1));

        jLabel2.setText("Preço:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 89, 57, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Cadastrar Produtos");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 0, -1, -1));

        ButtonCadastro.setText("Cadastrar");
        ButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 203, 338, -1));

        ButtonMenu.setText("Menu");
        ButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 232, 338, -1));

        jLabel4.setText("Quantidade:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 147, -1, -1));

        jComboqtd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        jComboqtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboqtdActionPerformed(evt);
            }
        });
        getContentPane().add(jComboqtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 147, -1, -1));
        getContentPane().add(TextPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 109, 338, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina-mecanica1 (1).jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, 1, 560, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCadastroActionPerformed

    private void ButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCadastroActionPerformed
        int x;
        String y;
        x = Integer.parseInt((String) jComboqtd.getSelectedItem());
        y = ((String)TextPreco.getText());
        if ( !"".equals(y) && !TextCadastro.getText().equals("")  ) {
            Estoque est = new Estoque();
            est.setNome(TextCadastro.getText());
            est.setPreco(Double.parseDouble(TextPreco.getText()));
            est.setQuantidade(x);
            crudEstoque crud = new crudEstoque();
            crud.create(est);
            JOptionPane.showMessageDialog(this, "Nome do produto: " + TextCadastro.getText() + " Preco: " + Double.parseDouble(TextPreco.getText()) + " Quantidade: " + x,
                    "Cadastro realizado com sucesso", JOptionPane.INFORMATION_MESSAGE);
            TextCadastro.setText("");
            TextPreco.setText("");

        } else {
            JOptionPane.showMessageDialog(rootPane, "Insira o texto");
        }
    }//GEN-LAST:event_ButtonCadastroActionPerformed

    private void ButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenuActionPerformed
        Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonMenuActionPerformed

    private void jComboqtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboqtdActionPerformed

    }//GEN-LAST:event_jComboqtdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCadastro;
    private javax.swing.JButton ButtonMenu;
    public javax.swing.JTextField TextCadastro;
    private javax.swing.JTextField TextPreco;
    public javax.swing.JComboBox<String> jComboqtd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
