
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lecox
 */
public class Editar extends javax.swing.JFrame {

    /**
     * Creates new form Editar
     */
    public Editar() {
        
     
        initComponents();
        readjTableEdit();
         this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEdit = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ButtonAlterar = new javax.swing.JButton();
        ButtonMenu = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        TextProdEditar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TextPrecoEdit = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboqtdEdit = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Preço Un", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEditMouseClicked(evt);
            }
        });
        jTableEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableEditKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableEdit);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, 533, 232));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Editar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 0, -1, -1));

        ButtonAlterar.setText("Alterar");
        ButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 341, 375, -1));

        ButtonMenu.setText("Menu");
        ButtonMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMenuActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 399, 375, -1));

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 370, 375, -1));

        TextProdEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextProdEditarActionPerformed(evt);
            }
        });
        getContentPane().add(TextProdEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, 157, -1));

        jLabel2.setText("Produto:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, -1, -1));

        TextPrecoEdit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        TextPrecoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrecoEditActionPerformed(evt);
            }
        });
        getContentPane().add(TextPrecoEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 67, 88, -1));

        jLabel3.setText("Preço:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 47, -1, -1));

        jComboqtdEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        jComboqtdEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboqtdEditActionPerformed(evt);
            }
        });
        getContentPane().add(jComboqtdEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 65, 56, -1));

        jLabel4.setText("Quantidade");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 45, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\java programas\\Programação Orientada a objetos\\Trabalho2\\src\\istockphoto-1175643252-640x640.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 560, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void readjTableEdit() {
        DefaultTableModel modelTable = (DefaultTableModel) jTableEdit.getModel();
        modelTable.setNumRows(0);
        Estoque est = new Estoque();
        crudEstoque crud = new crudEstoque();
        for (Estoque e : crud.read(est)) {

            modelTable.addRow(new Object[]{
                e.getCodProduto(),
                e.getNome(),
                e.getPreco(),
                e.getQuantidade()
            });

        }

    }

    private void ButtonMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMenuActionPerformed
        Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonMenuActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int linha, coluna, dado;
        crudEstoque crud = new crudEstoque();
        Estoque est = new Estoque();

        linha = jTableEdit.getSelectedRow();
        dado = (int) jTableEdit.getValueAt(linha, 0);
        est.setCodProduto(dado);
        crud.delete(est);
        JOptionPane.showMessageDialog(rootPane, "Dados Excluidos com sucesso");
        readjTableEdit();

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void ButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAlterarActionPerformed

        crudEstoque crud = new crudEstoque();
        Estoque est = new Estoque();

        int x;
        x = Integer.parseInt((String) jComboqtdEdit.getSelectedItem());
        if (jTableEdit.getSelectedRow() != -1) {

            est.setNome(TextProdEditar.getText());
            est.setPreco(Double.parseDouble((TextPrecoEdit.getText())));
            est.setQuantidade(x);
            est.setCodProduto((int) jTableEdit.getValueAt(jTableEdit.getSelectedRow(), 0));
            crud.update(est);
            JOptionPane.showMessageDialog(rootPane, "Dados Alterados com sucesso");
            readjTableEdit();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Você não selecionou dados para alterar");
        }
    }//GEN-LAST:event_ButtonAlterarActionPerformed


    private void TextProdEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextProdEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextProdEditarActionPerformed

    private void TextPrecoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrecoEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrecoEditActionPerformed

    private void jComboqtdEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboqtdEditActionPerformed

    }//GEN-LAST:event_jComboqtdEditActionPerformed

    private void jTableEditKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableEditKeyReleased

    }//GEN-LAST:event_jTableEditKeyReleased

    private void jTableEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEditMouseClicked
          
        if (jTableEdit.getSelectedRow() != -1) {
            TextProdEditar.setText((String) jTableEdit.getValueAt(jTableEdit.getSelectedRow(), 1));
            TextPrecoEdit.setText(jTableEdit.getValueAt(jTableEdit.getSelectedRow(), 2).toString());
            jComboqtdEdit.setSelectedIndex((int) jTableEdit.getValueAt(jTableEdit.getSelectedRow(), 3)-1);
        }

    }//GEN-LAST:event_jTableEditMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAlterar;
    private javax.swing.JButton ButtonMenu;
    public javax.swing.JFormattedTextField TextPrecoEdit;
    public javax.swing.JTextField TextProdEditar;
    private javax.swing.JButton jButtonExcluir;
    public javax.swing.JComboBox<String> jComboqtdEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableEdit;
    // End of variables declaration//GEN-END:variables
}
