
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author lecox
 */
public class Visualizar extends javax.swing.JFrame {

    /**
     * Creates new form Visualizar
     */
    public Visualizar() {
        this.setResizable(false);

        initComponents();

        readjTableVisu();
        totalPrecoQuantidade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVisu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ButtonRetornaMenu = new javax.swing.JButton();
        TextBusca = new javax.swing.JTextField();
        jButtonBusca = new javax.swing.JButton();
        jLabelTotal = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelTotalQuantidade = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelTotalItens = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableVisu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Preço Un", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableVisu);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, 547, 275));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Visualizar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 0, 88, -1));

        ButtonRetornaMenu.setText("Menu");
        ButtonRetornaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRetornaMenuActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonRetornaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 357, 271, -1));
        getContentPane().add(TextBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 48, 156, -1));

        jButtonBusca.setText("Buscar");
        jButtonBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 47, -1, -1));

        jLabelTotal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotal.setLabelFor(jLabel2);
        jLabelTotal.setToolTipText("");
        getContentPane().add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 357, 140, 14));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Preço:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 357, -1, -1));

        jLabelTotalQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelTotalQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 377, 110, 18));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total Quantidade:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 377, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Itens:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 397, -1, 15));

        jLabelTotalItens.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelTotalItens, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 397, 84, 14));

        jLabel5.setIcon(new javax.swing.ImageIcon("D:\\java programas\\Programação Orientada a objetos\\Trabalho2\\src\\istockphoto-1175643252-640x640.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 580, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRetornaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRetornaMenuActionPerformed
        Menu men = new Menu();
        men.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonRetornaMenuActionPerformed

    private void jButtonBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaActionPerformed
        readjTableBusca(TextBusca.getText());
    }//GEN-LAST:event_jButtonBuscaActionPerformed

    public void totalPrecoQuantidade() {
        crudEstoque crud = new crudEstoque();
        Estoque est = new Estoque();
        crud.soma(est);

        jLabelTotal.setText(String.valueOf(est.getTotal()));
        jLabelTotalQuantidade.setText(String.valueOf(est.getTotalQuantidade()));
        jLabelTotalItens.setText(String.valueOf(est.getQuantidadeItens()));

    }

    public void readjTableVisu() {
        DefaultTableModel modelTable = (DefaultTableModel) jTableVisu.getModel();
        modelTable.setNumRows(0);
        Estoque est = new Estoque();
        crudEstoque crud = new crudEstoque();
        // for each do objeto estoque que vai ler do banco de dados no método read e setar as variaveis na classe Estoque, aqui dentro do for vai dar
        // um get e selecionar em cada linha com sua respectiva coluna
        for (Estoque e : crud.read(est)) {

            modelTable.addRow(new Object[]{
                e.getCodProduto(),
                e.getNome(),
                e.getPreco(),
                e.getQuantidade()
            });

        }

    }

    public void readjTableBusca(String desc) {
        DefaultTableModel modelTable = (DefaultTableModel) jTableVisu.getModel();
        modelTable.setNumRows(0);
        Estoque est = new Estoque();
        crudEstoque crud = new crudEstoque();
        for (Estoque e : crud.busca(desc)) {

            modelTable.addRow(new Object[]{
                e.getCodProduto(),
                e.getNome(),
                e.getPreco(),
                e.getQuantidade()
            });

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRetornaMenu;
    private javax.swing.JTextField TextBusca;
    private javax.swing.JButton jButtonBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JLabel jLabelTotalItens;
    private javax.swing.JLabel jLabelTotalQuantidade;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableVisu;
    // End of variables declaration//GEN-END:variables
}
